app:
  name: "IMVU Insight API"
  env: "prod"
  api_v1_prefix: "/api/v1"
  root_path: "/insight/api"

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "imvu"
  password: "change_me"
  db: "imvu_insight"
  echo: false

